server:
  port: 9527

spring:
  application:
    name: microservicecloud-zuul-getway

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: getaway-9527.com
    prefer-ip-address: true


info:
  app.name: tomxwd-microservicecloud
  company.name: www.tomxwd.top
  build.artifactId: $project.artifactId$
  bulid.version: $project.version$
zuul:
  routes:
    mydept.serviceId: microservicecloud-dept
    mydept.path: /mydept/**
  ignored-services: "*"
  prefix: /tomxwd
#  ignored-services: microservicecloud-dept